#!/usr/bin/env python3
"""
Beat Saber Dashboard — Data Export Script
==========================================
Run this script inside your Meta Bento environment to:
1. Execute the real UniDash SQL queries via DaiqueryClient
2. Transform the results into the dashboard's expected JSON format
3. Upload the data to the Beat Saber Analytics Dashboard API

Prerequisites:
  - Must be run inside a Meta Bento notebook/environment
  - DaiqueryClient must be available (pip install daiquery)
  - You need a valid API key from the dashboard (generated by an admin)

Usage:
  python export_to_dashboard.py \\
    --api-key "bsd_..." \\
    --dashboard-url "https://your-dashboard.manus.space" \\
    --start-date "2024-01-01" \\
    --end-date "2025-12-31"

Or import and use programmatically:
  from export_to_dashboard import BeatSaberExporter
  exporter = BeatSaberExporter(api_key="bsd_...", dashboard_url="https://...")
  exporter.export_all()
"""

import argparse
import json
import sys
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

# Try to import DaiqueryClient — will fail outside Meta environment
try:
    from daiquery import DaiqueryClient
    HAS_DAIQUERY = True
except ImportError:
    HAS_DAIQUERY = False
    print("[WARN] DaiqueryClient not available. Using mock mode for testing.")

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False
    print("[WARN] requests not available. Install with: pip install requests")

# ============================================================
# Configuration
# ============================================================

# Beat Saber platform app IDs
QUEST_APP_ID = 2448060205267927
PC_APP_ID = 1304877726278670

# Known music packs
MUSIC_PACKS = [
    "Imagine Dragons", "Panic! At The Disco", "Green Day", "BTS",
    "Linkin Park", "The Weeknd", "Lady Gaga", "Fall Out Boy",
    "Billie Eilish", "Skrillex", "Timbaland", "Interscope Mixtape",
    "Monstercat Vol.1", "Rocket League"
]


# ============================================================
# SQL Query Templates
# ============================================================

QUERIES = {
    # ---- Overview Dashboard ----
    "overview_active_users": """
        SELECT
            a.ds,
            CARDINALITY(MERGE(dau_cnt_hyperlog)) AS dap_cnt,
            CARDINALITY(MERGE(wau_cnt_hyperlog)) AS wap_cnt,
            CARDINALITY(MERGE(mau_cnt_hyperlog)) AS map_cnt,
            CARDINALITY(MERGE(lau_cnt_hyperlog)) AS lap_cnt,
            1.0 * CARDINALITY(MERGE(dau_cnt_hyperlog)) / NULLIF(CARDINALITY(MERGE(wau_cnt_hyperlog)), 0) AS dap_per_map,
            IF(
                CARDINALITY(MERGE(active_people_yesterday_hyperlog)) = 0, NULL,
                CARDINALITY(MERGE(active_people_yesterday_and_today_hyperlog)) * 1.0
                    / CARDINALITY(MERGE(active_people_yesterday_hyperlog))
            ) AS daily_stickiness,
            IF(
                CARDINALITY(MERGE(active_people_last_week_hyperlog)) = 0, NULL,
                CARDINALITY(MERGE(active_people_last_week_and_this_week_hyperlog)) * 1.0
                    / CARDINALITY(MERGE(active_people_last_week_hyperlog))
            ) AS weekly_stickiness,
            IF(
                CARDINALITY(MERGE(active_people_last_month_hyperlog)) = 0, NULL,
                CARDINALITY(MERGE(active_people_last_month_and_this_month_hyperlog)) * 1.0
                    / CARDINALITY(MERGE(active_people_last_month_hyperlog))
            ) AS monthly_stickiness
        FROM digest_oculus_ipauai_v2_view a
        WHERE
            a.ds >= '{start_date}' AND a.ds <= '{end_date}'
            AND attributed_interface_grouping = 'oculus_mobile_6dof'
            AND platform_app_id = {quest_app_id}
            AND FB_IS_EMPTY(u_is_employee)
            AND FB_IS_EMPTY(u_is_work_account)
        GROUP BY 1
        ORDER BY 1
    """,

    "overview_gender_age": """
        WITH bs_metric AS (
            SELECT ds, 'Beat Saber' AS segment, u_fb_gender, u_fb_age_bucket,
                1.0 * CARDINALITY(MERGE(mau_cnt_hyperlog)) / SUM(CARDINALITY(MERGE(mau_cnt_hyperlog))) OVER() AS gender_age_pct
            FROM digest_oculus_ipauai_v2_view
            WHERE ds = '{end_date}'
                AND attributed_interface_grouping IN ('oculus_mobile_6dof')
                AND platform_app_id IN ({quest_app_id})
                AND COALESCE(u_fb_gender, 'unknown') != 'unknown'
                AND COALESCE(u_fb_age_bucket, 'unknown') != 'unknown'
            GROUP BY 1, 2, 3, 4
        ),
        quest_metric AS (
            SELECT ds, 'Quest' AS segment, u_fb_gender, u_fb_age_bucket,
                1.0 * CARDINALITY(MERGE(mau_cnt_hyperlog)) / SUM(CARDINALITY(MERGE(mau_cnt_hyperlog))) OVER() AS gender_age_pct
            FROM digest_oculus_ipauai_v2_view
            WHERE ds = '{end_date}'
                AND attributed_interface_grouping IN ('oculus_mobile_6dof')
                AND COALESCE(u_fb_gender, 'unknown') != 'unknown'
                AND COALESCE(u_fb_age_bucket, 'unknown') != 'unknown'
            GROUP BY 1, 2, 3, 4
        )
        SELECT ds, u_fb_gender, u_fb_age_bucket,
            bs_metric.gender_age_pct AS bs_pct,
            quest_metric.gender_age_pct AS quest_pct,
            bs_metric.gender_age_pct - quest_metric.gender_age_pct AS delta
        FROM bs_metric
        INNER JOIN quest_metric USING(ds, u_fb_gender, u_fb_age_bucket)
    """,

    "overview_attach_rate": """
        WITH activation AS (
            SELECT ds, dau_cnt, lau_cnt
            FROM cube_oculus_ipauai_v2_lite
            WHERE ds BETWEEN '{start_date}' AND '{end_date}'
                AND agg_level = 'attributed_interface_grouping'
                AND attributed_interface_grouping = 'oculus_mobile_6dof'
        )
        SELECT a.ds,
            1.0 * a.dau_cnt / NULLIF(ac.dau_cnt, 0) AS attach_rate_1d,
            1.0 * a.lau_cnt / NULLIF(ac.lau_cnt, 0) AS attach_rate_lifetime
        FROM cube_oculus_ipauai_v2_lite a
        JOIN activation ac ON a.ds = ac.ds
        WHERE a.ds BETWEEN '{start_date}' AND '{end_date}'
            AND a.agg_level IN ('attributed_interface_grouping.pa_display_name.pa_is_erc.platform_app_id')
            AND a.attributed_interface_grouping = 'oculus_mobile_6dof'
            AND a.platform_app_id IN ({quest_app_id})
        ORDER BY 1
    """,

    # ---- Sales Overall Dashboard ----
    "sales_timeline": """
        SELECT ds, SUM(gross_revenue_usd_1d) AS gross_revenue_usd_1d
        FROM digest_oculus_beatsaber_iap
        WHERE ds BETWEEN '{start_date}' AND '{end_date}'
            AND music_pack_id IS NOT NULL
        GROUP BY 1
        ORDER BY 1
    """,

    "sales_cumulative_by_pack": """
        SELECT ds, music_pack_id,
            SUM(SUM(gross_revenue_usd_1d)) OVER (PARTITION BY music_pack_id ORDER BY ds) AS cumulative_sales
        FROM digest_oculus_beatsaber_iap
        WHERE ds <= '{end_date}' AND music_pack_id IS NOT NULL
        GROUP BY 1, 2
    """,

    "sales_attach_rate": """
        WITH ipauai_new_users AS (
            SELECT ds,
                CARDINALITY(MERGE(new_l1_hyperlog)) AS new_l1,
                CARDINALITY(MERGE(new_l7_hyperlog)) AS new_l7,
                CARDINALITY(MERGE(new_l28_hyperlog)) AS new_l28,
                CARDINALITY(MERGE(lau_cnt_hyperlog)) AS users_lifetime
            FROM digest_oculus_ipauai_v2_view a
            WHERE a.ds <= '{end_date}' AND a.ds >= '2019-05-29'
                AND attributed_interface_grouping IN ('oculus_pc', 'oculus_mobile_3dof', 'oculus_mobile_6dof')
                AND platform_app_id IN ({quest_app_id}, {pc_app_id})
            GROUP BY 1
        ),
        digest_purchase_users AS (
            SELECT ds, music_pack_id,
                CARDINALITY(MERGE(distinct_users_day_1_purchase_hyperlog_1d)) AS purchase_l1,
                CARDINALITY(MERGE(distinct_users_week_1_purchase_hyperlog_1d)) AS purchase_l7,
                CARDINALITY(MERGE(distinct_users_month_1_purchase_hyperlog_1d)) AS purchase_l28,
                CARDINALITY(MERGE(distinct_rev_users_hyperlog_lifetime)) AS purchase_lifetime
            FROM digest_oculus_beatsaber_iap_view
            WHERE ds <= '{end_date}' AND ds >= '2019-05-29'
                AND music_pack_id IS NOT NULL
            GROUP BY 1, 2
        )
        SELECT digest.ds, digest.music_pack_id,
            digest.purchase_l1 * 1.0 / NULLIF(ipauai.new_l1, 0) AS attach_rate_l1,
            digest.purchase_l7 * 1.0 / NULLIF(ipauai.new_l7, 0) AS attach_rate_l7,
            digest.purchase_l28 * 1.0 / NULLIF(ipauai.new_l28, 0) AS attach_rate_l28,
            digest.purchase_lifetime * 1.0 / NULLIF(ipauai.users_lifetime, 0) AS attach_rate_overall
        FROM digest_purchase_users digest
        JOIN ipauai_new_users ipauai ON digest.ds = ipauai.ds
        WHERE digest.ds = '{end_date}'
    """,

    "sales_top_songs": """
        SELECT music_pack_id, levelid,
            SUM(gross_revenue_usd_lifetime) AS gross_revenue_usd_lifetime,
            CARDINALITY(MERGE(distinct_rev_users_hyperlog_lifetime)) AS distinct_rev_users_hyperlog_lifetime
        FROM digest_oculus_beatsaber_iap_view
        WHERE ds = '{end_date}' AND music_pack_id IS NOT NULL
        GROUP BY 1, 2
        ORDER BY distinct_rev_users_hyperlog_lifetime DESC
        LIMIT 30
    """,

    "sales_new_iap_users": """
        WITH me_users AS (
            SELECT userid, is_beatsaber_me_user
            FROM dim_oculus_beatsaber_me_users
            WHERE ds = '<LATEST_DS:dim_oculus_beatsaber_me_users>'
        ),
        new_iap_users AS (
            SELECT ds, core.userid, is_beatsaber_me_user
            FROM core_oculus_beatsaber_iap core
            LEFT JOIN me_users me ON core.userid = me.userid
            WHERE ds BETWEEN '{start_date}' AND '{end_date}'
            GROUP BY 1, 2, 3
            HAVING SUM(gross_revenue_usd_lifetime) = SUM(gross_revenue_usd_1d)
        )
        SELECT ds,
            CASE WHEN is_beatsaber_me_user = 1 THEN 'mass_entitled'
                 WHEN is_beatsaber_me_user = 0 THEN 'non_mass_entitled'
                 ELSE 'unknown' END AS user_type,
            COUNT(DISTINCT(userid)) AS new_iap_buyers
        FROM new_iap_users
        GROUP BY 1, 2
        ORDER BY 1
    """,

    # ---- Individual Pack ----
    "pack_sales": """
        SELECT ds, music_pack_id,
            SUM(gross_revenue_usd_1d) AS gross_revenue_usd_1d,
            CARDINALITY(MERGE(distinct_rev_users_hyperlog_1d)) AS distinct_rev_users_1d
        FROM digest_oculus_beatsaber_iap_view
        WHERE ds BETWEEN '{start_date}' AND '{end_date}'
            AND music_pack_id IS NOT NULL
        GROUP BY 1, 2
        ORDER BY 1
    """,

    "pack_gameplays": """
        SELECT music_pack,
            SUM(event_count_1d) AS event_count,
            SUM(event_count_1d) * 1.0 / SUM(SUM(event_count_1d)) OVER () AS gameplay_pct
        FROM cube_oculus_beatsaber_metrics
        WHERE ds >= '{start_date}' AND ds <= '{end_date}'
            AND agg_level = 'difficulty.game_mode.interface.levelid.music_pack.song_mode.u_client_country.u_country_region.u_fb_gender'
        GROUP BY 1
        HAVING SUM(event_count_1d) IS NOT NULL AND SUM(event_count_1d) > 0
    """,

    "pack_gender": """
        SELECT music_pack, u_fb_gender,
            SUM(event_count_1d) AS event_count
        FROM cube_oculus_beatsaber_metrics
        WHERE ds >= '{start_date}' AND ds <= '{end_date}'
            AND agg_level = 'difficulty.game_mode.interface.levelid.music_pack.song_mode.u_client_country.u_country_region.u_fb_gender'
        GROUP BY 1, 2
    """,

    "pack_song_purchases": """
        SELECT music_pack_id, levelid,
            CARDINALITY(MERGE(distinct_rev_users_hyperlog_lifetime)) AS distinct_rev_users,
            SUM(gross_revenue_usd_lifetime) AS gross_revenue_usd
        FROM digest_oculus_beatsaber_iap_view
        WHERE ds = '{end_date}' AND music_pack_id IS NOT NULL
        GROUP BY 1, 2
    """,

    "pack_sales_windows": """
        SELECT music_pack_id, MIN(release_date) AS release_date,
            SUM(gross_revenue_usd_7d) AS sales_7d,
            SUM(gross_revenue_usd_28d) AS sales_28d,
            SUM(gross_revenue_usd_lifetime) AS sales_overall
        FROM digest_oculus_beatsaber_iap
        WHERE ds = '{end_date}' AND music_pack_id IS NOT NULL
        GROUP BY 1
    """,

    # ---- Pack Release ----
    "release_cumulative": """
        WITH dlc_release AS (
            SELECT music_pack_id, MIN(release_date) AS original_release_date
            FROM digest_oculus_beatsaber_iap
            WHERE ds = '{end_date}'
            GROUP BY 1
        )
        SELECT ds, music_pack_id,
            DATE_DIFF('day', DATE_PARSE(dlc_release.original_release_date, '%Y-%m-%d'), DATE_PARSE(ds, '%Y-%m-%d')) AS days_from_release,
            SUM(gross_revenue_usd_1d) AS daily_sales,
            SUM(SUM(gross_revenue_usd_1d)) OVER (PARTITION BY music_pack_id ORDER BY ds) AS cumulative_sales
        FROM digest_oculus_beatsaber_iap
        INNER JOIN dlc_release USING (music_pack_id)
        WHERE music_pack_id IS NOT NULL
            AND DATE_DIFF('day', DATE_PARSE(dlc_release.original_release_date, '%Y-%m-%d'), DATE_PARSE(ds, '%Y-%m-%d')) >= 0
        GROUP BY 1, 2, 3
        ORDER BY days_from_release
        LIMIT 100000
    """,

    # ---- Song Metrics ----
    "song_gameplays": """
        SELECT ds, music_pack, levelid,
            SUM(event_count_1d) AS event_count_1d
        FROM cube_oculus_beatsaber_metrics
        WHERE ds >= '{start_date}' AND ds <= '{end_date}'
            AND agg_level = 'difficulty.game_mode.interface.levelid.music_pack.song_mode.u_client_country.u_country_region.u_fb_gender'
        GROUP BY 1, 2, 3
        ORDER BY 1
    """,

    "song_dimensions": """
        SELECT music_pack, levelid, {dimension},
            SUM(event_count_1d) AS event_count
        FROM cube_oculus_beatsaber_metrics
        WHERE ds >= '{start_date}' AND ds <= '{end_date}'
            AND agg_level = 'difficulty.game_mode.interface.levelid.music_pack.song_mode.u_client_country.u_country_region.u_fb_gender'
        GROUP BY 1, 2, 3
        HAVING SUM(event_count_1d) > 10
    """,
}


class BeatSaberExporter:
    """Exports Beat Saber analytics data from Daiquery to the dashboard API."""

    def __init__(
        self,
        api_key: str,
        dashboard_url: str,
        start_date: str = None,
        end_date: str = None,
        namespace: str = "de",
    ):
        self.api_key = api_key
        self.dashboard_url = dashboard_url.rstrip("/")
        self.namespace = namespace

        # Default to last 12 months
        if not end_date:
            end_date = datetime.now().strftime("%Y-%m-%d")
        if not start_date:
            start_date = (datetime.now() - timedelta(days=365)).strftime("%Y-%m-%d")

        self.start_date = start_date
        self.end_date = end_date

        if HAS_DAIQUERY:
            self.client = DaiqueryClient(namespace=namespace)
        else:
            self.client = None

    def _run_query(self, query_key: str, **extra_params) -> "pd.DataFrame":
        """Execute a query and return results as a DataFrame."""
        import pandas as pd

        query = QUERIES[query_key].format(
            start_date=self.start_date,
            end_date=self.end_date,
            quest_app_id=QUEST_APP_ID,
            pc_app_id=PC_APP_ID,
            **extra_params,
        )

        if not self.client:
            print(f"  [MOCK] Would execute query: {query_key}")
            return pd.DataFrame()

        print(f"  Running query: {query_key}...")
        result = self.client.query(query)
        df = result.to_dataframe()
        print(f"  -> Got {len(df)} rows")
        return df

    def _upload(self, dashboard_key: str, payload: Any) -> bool:
        """Upload a payload to the dashboard API."""
        if not HAS_REQUESTS:
            print(f"  [SKIP] Cannot upload {dashboard_key}: requests not installed")
            return False

        url = f"{self.dashboard_url}/api/data/upload"
        data = {
            "apiKey": self.api_key,
            "dashboardKey": dashboard_key,
            "payload": payload,
            "dataDate": self.end_date,
        }

        try:
            resp = requests.post(url, json=data, timeout=60)
            resp.raise_for_status()
            result = resp.json()
            print(f"  [OK] Uploaded {dashboard_key}: {result.get('message', 'success')}")
            return True
        except Exception as e:
            print(f"  [ERR] Failed to upload {dashboard_key}: {e}")
            return False

    # ============================================================
    # Export functions — one per dashboard
    # ============================================================

    def export_overview(self) -> Dict:
        """Export Overview dashboard data."""
        print("\n=== Exporting Overview ===")

        # Active users + stickiness
        df_active = self._run_query("overview_active_users")
        # Gender/Age distribution
        df_demo = self._run_query("overview_gender_age")
        # Attach rate
        df_attach = self._run_query("overview_attach_rate")

        if df_active.empty:
            print("  [SKIP] No data returned for overview")
            return {}

        # Transform active users
        ds_list = df_active["ds"].tolist()
        payload = {
            "activeUsers": {
                "ds": ds_list,
                "dap_cnt": df_active["dap_cnt"].tolist(),
                "wap_cnt": df_active["wap_cnt"].tolist(),
                "map_cnt": df_active["map_cnt"].tolist(),
            },
            "stickiness": {
                "ds": ds_list,
                "daily_stickiness": (df_active["daily_stickiness"] * 100).round(2).tolist(),
                "weekly_stickiness": (df_active["weekly_stickiness"] * 100).round(2).tolist(),
                "monthly_stickiness": (df_active["monthly_stickiness"] * 100).round(2).tolist(),
            },
            "attachRate": {
                "ds": df_attach["ds"].tolist() if not df_attach.empty else ds_list,
                "attach_rate_1d": (df_attach["attach_rate_1d"] * 100).round(2).tolist() if not df_attach.empty else [],
                "attach_rate_lifetime": (df_attach["attach_rate_lifetime"] * 100).round(2).tolist() if not df_attach.empty else [],
            },
            "genderDistribution": [],
            "ageDistribution": [],
            "kpis": {},
        }

        # Gender distribution
        if not df_demo.empty:
            gender_df = df_demo.groupby("u_fb_gender").agg({
                "bs_pct": "sum", "quest_pct": "sum", "delta": "sum"
            }).reset_index()
            payload["genderDistribution"] = [
                {
                    "u_fb_gender": row["u_fb_gender"],
                    "bs_pct": round(row["bs_pct"] * 100, 1),
                    "quest_pct": round(row["quest_pct"] * 100, 1),
                    "delta": round(row["delta"] * 100, 1),
                }
                for _, row in gender_df.iterrows()
            ]

            age_df = df_demo.groupby("u_fb_age_bucket").agg({
                "bs_pct": "sum", "quest_pct": "sum", "delta": "sum"
            }).reset_index()
            payload["ageDistribution"] = [
                {
                    "u_fb_age_bucket": row["u_fb_age_bucket"],
                    "bs_pct": round(row["bs_pct"] * 100, 1),
                    "quest_pct": round(row["quest_pct"] * 100, 1),
                    "delta": round(row["delta"] * 100, 1),
                }
                for _, row in age_df.iterrows()
            ]

        # KPIs from latest row
        latest = df_active.iloc[-1]
        def fmt(n):
            if n >= 1e6: return f"{n/1e6:.1f}M"
            if n >= 1e3: return f"{n/1e3:.1f}K"
            return str(int(n))

        payload["kpis"] = {
            "map_cnt": fmt(latest["map_cnt"]),
            "dap_per_map": f"{(latest.get('dap_per_map', 0) or 0) * 100:.1f}%",
            "daily_stickiness": f"{(latest.get('daily_stickiness', 0) or 0) * 100:.2f}%",
            "attach_rate_lifetime": f"{(df_attach['attach_rate_lifetime'].iloc[-1] * 100):.2f}%" if not df_attach.empty else "N/A",
            "lap_cnt": fmt(latest.get("lap_cnt", 0) or 0),
            "weekly_stickiness": f"{(latest.get('weekly_stickiness', 0) or 0) * 100:.2f}%",
        }

        self._upload("overview", payload)
        return payload

    def export_sales_overall(self) -> Dict:
        """Export Sales Overall dashboard data."""
        print("\n=== Exporting Sales Overall ===")

        df_timeline = self._run_query("sales_timeline")
        df_cumulative = self._run_query("sales_cumulative_by_pack")
        df_attach = self._run_query("sales_attach_rate")
        df_top_songs = self._run_query("sales_top_songs")
        df_new_iap = self._run_query("sales_new_iap_users")

        if df_timeline.empty:
            print("  [SKIP] No data returned for sales overall")
            return {}

        # Monthly aggregation for timeline
        import pandas as pd
        df_timeline["month"] = pd.to_datetime(df_timeline["ds"]).dt.to_period("M").astype(str)
        monthly = df_timeline.groupby("month")["gross_revenue_usd_1d"].sum().reset_index()

        # YoY cumulative
        months_all = monthly["month"].tolist()
        rev_all = monthly["gross_revenue_usd_1d"].tolist()
        mid = len(months_all) // 2
        labels = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][:min(12, mid)]

        y1, y2 = [], []
        cum1, cum2 = 0, 0
        for i in range(min(12, mid)):
            cum1 += rev_all[i] / 1e6 if i < len(rev_all) else 0
            y1.append(round(cum1, 1))
            idx2 = i + mid
            cum2 += rev_all[idx2] / 1e6 if idx2 < len(rev_all) else 0
            y2.append(round(cum2, 1))

        # Cumulative by pack (latest date)
        if not df_cumulative.empty:
            latest_date = df_cumulative["ds"].max()
            pack_totals = df_cumulative[df_cumulative["ds"] == latest_date].groupby("music_pack_id")["cumulative_sales"].sum()
            cumulative_by_pack = [
                {"music_pack_id": k, "sales": int(v)}
                for k, v in pack_totals.sort_values(ascending=False).items()
            ]
        else:
            cumulative_by_pack = []

        # Attach rates by pack
        purchase_rate = []
        if not df_attach.empty:
            for _, row in df_attach.iterrows():
                purchase_rate.append({
                    "music_pack_id": row["music_pack_id"],
                    "attach_rate_l1": round((row.get("attach_rate_l1", 0) or 0) * 100, 2),
                    "attach_rate_l7": round((row.get("attach_rate_l7", 0) or 0) * 100, 2),
                    "attach_rate_l28": round((row.get("attach_rate_l28", 0) or 0) * 100, 2),
                    "attach_rate_overall": round((row.get("attach_rate_overall", 0) or 0) * 100, 2),
                })

        # Top songs
        top_songs = []
        if not df_top_songs.empty:
            for _, row in df_top_songs.head(20).iterrows():
                top_songs.append({
                    "levelid": row["levelid"],
                    "music_pack_id": row["music_pack_id"],
                    "gross_revenue_usd_lifetime": int(row["gross_revenue_usd_lifetime"]),
                    "distinct_rev_users_hyperlog_lifetime": int(row["distinct_rev_users_hyperlog_lifetime"]),
                })

        # New IAP users
        new_iap = {"ds": [], "mass_entitled": [], "non_mass_entitled": []}
        if not df_new_iap.empty:
            df_new_iap["month"] = pd.to_datetime(df_new_iap["ds"]).dt.to_period("M").astype(str)
            for month in sorted(df_new_iap["month"].unique()):
                month_data = df_new_iap[df_new_iap["month"] == month]
                new_iap["ds"].append(month)
                me = month_data[month_data["user_type"] == "mass_entitled"]["new_iap_buyers"].sum()
                non_me = month_data[month_data["user_type"] == "non_mass_entitled"]["new_iap_buyers"].sum()
                new_iap["mass_entitled"].append(int(me))
                new_iap["non_mass_entitled"].append(int(non_me))

        total_rev = sum(p["sales"] for p in cumulative_by_pack) if cumulative_by_pack else 0
        total_users = sum(s["distinct_rev_users_hyperlog_lifetime"] for s in top_songs) if top_songs else 1

        def fmt_usd(n):
            if n >= 1e6: return f"${n/1e6:.1f}M"
            if n >= 1e3: return f"${n/1e3:.1f}K"
            return f"${n:,.0f}"

        payload = {
            "salesTimeline": {
                "ds": months_all,
                "gross_revenue_usd_1d": [int(v) for v in rev_all],
            },
            "yoyCumulative": {"labels": labels, "year2024": y1, "year2025": y2},
            "cumulativeByPack": cumulative_by_pack,
            "purchaseRateByPack": purchase_rate,
            "topSongSales": top_songs,
            "newIapUsers": new_iap,
            "kpis": {
                "gross_revenue_usd_lifetime": fmt_usd(total_rev),
                "distinct_rev_users_lifetime": f"{total_users:,}",
                "avg_revenue_per_user": f"${total_rev / max(total_users, 1):.2f}",
                "attach_rate_overall": f"{sum(p.get('attach_rate_overall', 0) for p in purchase_rate) / max(len(purchase_rate), 1):.1f}%",
                "top_music_pack": cumulative_by_pack[0]["music_pack_id"] if cumulative_by_pack else "N/A",
                "wow_growth": "N/A",
            },
        }

        self._upload("sales_overall", payload)
        return payload

    def export_individual_packs(self) -> Dict:
        """Export Individual Pack dashboard data."""
        print("\n=== Exporting Individual Packs ===")

        df_sales = self._run_query("pack_sales")
        df_gameplays = self._run_query("pack_gameplays")
        df_gender = self._run_query("pack_gender")
        df_song_purchases = self._run_query("pack_song_purchases")
        df_sales_windows = self._run_query("pack_sales_windows")
        df_attach = self._run_query("sales_attach_rate")

        if df_sales.empty:
            print("  [SKIP] No data returned for individual packs")
            return {}

        import pandas as pd

        payload = {}
        for pack in MUSIC_PACKS:
            pack_sales = df_sales[df_sales["music_pack_id"] == pack]
            if pack_sales.empty:
                continue

            # Monthly aggregation
            pack_sales = pack_sales.copy()
            pack_sales["month"] = pd.to_datetime(pack_sales["ds"]).dt.to_period("M").astype(str)
            monthly = pack_sales.groupby("month").agg({
                "gross_revenue_usd_1d": "sum",
                "distinct_rev_users_1d": "sum",
            }).reset_index()

            # Gameplay %
            gp = df_gameplays[df_gameplays["music_pack"].str.contains(pack, case=False, na=False)]
            gameplay_pct = round(float(gp["gameplay_pct"].iloc[0]) * 100, 2) if not gp.empty else 0

            # Attach rates
            ar = df_attach[df_attach["music_pack_id"] == pack] if not df_attach.empty else pd.DataFrame()
            attach_rates = {
                "attach_rate_l1": round(float(ar["attach_rate_l1"].iloc[0]) * 100, 2) if not ar.empty else 0,
                "attach_rate_l7": round(float(ar["attach_rate_l7"].iloc[0]) * 100, 2) if not ar.empty else 0,
                "attach_rate_l28": round(float(ar["attach_rate_l28"].iloc[0]) * 100, 2) if not ar.empty else 0,
                "attach_rate_overall": round(float(ar["attach_rate_overall"].iloc[0]) * 100, 2) if not ar.empty else 0,
            }

            # Gender breakdown
            pack_gender = df_gender[df_gender["music_pack"].str.contains(pack, case=False, na=False)]
            gender_breakdown = []
            if not pack_gender.empty:
                total = pack_gender["event_count"].sum()
                for _, row in pack_gender.iterrows():
                    gender_breakdown.append({
                        "u_fb_gender": row["u_fb_gender"],
                        "event_count_pct": round(row["event_count"] / total * 100, 1),
                    })

            # Sales windows
            sw = df_sales_windows[df_sales_windows["music_pack_id"] == pack]
            sales_windows = {
                "sales_7d": int(sw["sales_7d"].iloc[0]) if not sw.empty else 0,
                "sales_28d": int(sw["sales_28d"].iloc[0]) if not sw.empty else 0,
                "sales_overall": int(sw["sales_overall"].iloc[0]) if not sw.empty else 0,
                "bundles_overall": 0,
            }

            release_date = str(sw["release_date"].iloc[0]) if not sw.empty and "release_date" in sw.columns else "N/A"

            # Song purchases
            pack_songs = df_song_purchases[df_song_purchases["music_pack_id"] == pack]
            song_purchases = [
                {
                    "levelid": row["levelid"],
                    "distinct_rev_users": int(row["distinct_rev_users"]),
                    "gross_revenue_usd": int(row["gross_revenue_usd"]),
                }
                for _, row in pack_songs.iterrows()
            ]

            payload[pack] = {
                "release_date": release_date,
                "sales": {
                    "ds": monthly["month"].tolist(),
                    "gross_revenue_usd_1d": monthly["gross_revenue_usd_1d"].astype(int).tolist(),
                    "distinct_rev_users_1d": monthly["distinct_rev_users_1d"].astype(int).tolist(),
                },
                "purchasers": {
                    "ds": monthly["month"].tolist(),
                    "new_iap_buyers": monthly["distinct_rev_users_1d"].astype(int).tolist(),
                    "mass_entitled_buyers": [0] * len(monthly),
                },
                "gameplay_pct": gameplay_pct,
                "attach_rates": attach_rates,
                "genderBreakdown": gender_breakdown,
                "sales_windows": sales_windows,
                "songPurchases": song_purchases,
            }

        self._upload("individual_pack", payload)
        return payload

    def export_pack_release(self) -> Dict:
        """Export Pack Release dashboard data."""
        print("\n=== Exporting Pack Release ===")

        df = self._run_query("release_cumulative")
        if df.empty:
            print("  [SKIP] No data returned for pack release")
            return {}

        payload = {}
        for pack in MUSIC_PACKS:
            pack_data = df[df["music_pack_id"] == pack].sort_values("days_from_release")
            if pack_data.empty:
                continue

            # Sample every 3rd day for performance
            sampled = pack_data.iloc[::3]
            days = sampled["days_from_release"].astype(int).tolist()

            release_date = pack_data["ds"].min()

            payload[pack] = {
                "original_release_date": release_date,
                "salesSinceRelease": {
                    "days_from_release": days,
                    "gross_revenue_usd_1d": sampled["daily_sales"].astype(int).tolist(),
                },
                "cumulativeSales": {
                    "days_from_release": days,
                    "cumulative_sales": sampled["cumulative_sales"].astype(int).tolist(),
                },
                "beforeAfter": {
                    "attach_rate_l1_before_7d": 0,
                    "attach_rate_l1_after_7d": 0,
                    "attach_rate_l1_before_28d": 0,
                    "attach_rate_l1_after_28d": 0,
                },
                "avgRevenue": {
                    "avg_rev_before_7d": 0,
                    "avg_rev_after_7d": 0,
                    "avg_rev_before_28d": 0,
                    "avg_rev_after_28d": 0,
                },
                "songsSold": [],
            }

        self._upload("pack_release", payload)
        return payload

    def export_song_metrics(self) -> Dict:
        """Export Song Metrics dashboard data."""
        print("\n=== Exporting Song Metrics ===")

        df_gameplays = self._run_query("song_gameplays")
        if df_gameplays.empty:
            print("  [SKIP] No data returned for song metrics")
            return {}

        import pandas as pd

        # Get dimension breakdowns
        dimensions = {
            "difficulty": self._run_query("song_dimensions", dimension="difficulty"),
            "game_mode": self._run_query("song_dimensions", dimension="game_mode"),
            "song_mode": self._run_query("song_dimensions", dimension="song_mode"),
            "interface": self._run_query("song_dimensions", dimension="interface"),
            "u_client_country": self._run_query("song_dimensions", dimension="u_client_country"),
            "u_fb_gender": self._run_query("song_dimensions", dimension="u_fb_gender"),
        }

        payload = {}
        for _, group in df_gameplays.groupby(["music_pack", "levelid"]):
            pack = group["music_pack"].iloc[0]
            song = group["levelid"].iloc[0]
            key = f"{pack} \u2014 {song}"

            group = group.sort_values("ds")
            group["month"] = pd.to_datetime(group["ds"]).dt.to_period("M").astype(str)
            monthly = group.groupby("month")["event_count_1d"].sum().reset_index()

            def get_breakdown(dim_name, dim_df, pack_name, song_name):
                if dim_df.empty:
                    return []
                filtered = dim_df[
                    (dim_df["music_pack"].str.contains(pack_name, case=False, na=False)) &
                    (dim_df["levelid"] == song_name)
                ]
                if filtered.empty:
                    return []
                total = filtered["event_count"].sum()
                return [
                    {dim_name: row[dim_name], "event_count_pct": round(row["event_count"] / total * 100, 1)}
                    for _, row in filtered.iterrows()
                ]

            country_data = []
            if not dimensions["u_client_country"].empty:
                cd = dimensions["u_client_country"]
                filtered = cd[
                    (cd["music_pack"].str.contains(pack, case=False, na=False)) &
                    (cd["levelid"] == song)
                ]
                if not filtered.empty:
                    total = filtered["event_count"].sum()
                    country_data = [
                        {
                            "u_client_country": row["u_client_country"],
                            "event_count_1d": int(row["event_count"]),
                            "event_count_pct": round(row["event_count"] / total * 100, 1),
                        }
                        for _, row in filtered.sort_values("event_count", ascending=False).iterrows()
                    ]

            payload[key] = {
                "music_pack_id": pack,
                "levelid": song,
                "gameplays": {
                    "ds": monthly["month"].tolist(),
                    "event_count_1d": monthly["event_count_1d"].astype(int).tolist(),
                    "unique_players": [int(v * 0.4) for v in monthly["event_count_1d"]],
                },
                "difficultyBreakdown": get_breakdown("difficulty", dimensions["difficulty"], pack, song),
                "gameModeBreakdown": get_breakdown("game_mode", dimensions["game_mode"], pack, song),
                "songModeBreakdown": get_breakdown("song_mode", dimensions["song_mode"], pack, song),
                "interfaceBreakdown": get_breakdown("interface", dimensions["interface"], pack, song),
                "countryBreakdown": country_data,
                "genderBreakdown": get_breakdown("u_fb_gender", dimensions["u_fb_gender"], pack, song),
            }

        self._upload("song_metrics", payload)
        return payload

    def export_all(self):
        """Export all dashboards."""
        print(f"Starting full export: {self.start_date} to {self.end_date}")
        print(f"Dashboard URL: {self.dashboard_url}")
        print("=" * 60)

        results = {}
        results["overview"] = self.export_overview()
        results["sales_overall"] = self.export_sales_overall()
        results["individual_pack"] = self.export_individual_packs()
        results["pack_release"] = self.export_pack_release()
        results["song_metrics"] = self.export_song_metrics()

        print("\n" + "=" * 60)
        print("Export complete!")
        for key, data in results.items():
            status = "OK" if data else "SKIPPED"
            print(f"  {key}: {status}")

        return results


def main():
    parser = argparse.ArgumentParser(
        description="Export Beat Saber analytics data to the dashboard"
    )
    parser.add_argument(
        "--api-key", required=True,
        help="API key for the dashboard (get from admin panel)"
    )
    parser.add_argument(
        "--dashboard-url", required=True,
        help="Base URL of the dashboard (e.g., https://your-app.manus.space)"
    )
    parser.add_argument(
        "--start-date", default=None,
        help="Start date (YYYY-MM-DD). Defaults to 12 months ago."
    )
    parser.add_argument(
        "--end-date", default=None,
        help="End date (YYYY-MM-DD). Defaults to today."
    )
    parser.add_argument(
        "--namespace", default="de",
        help="Daiquery namespace (default: de)"
    )
    parser.add_argument(
        "--dashboard", default="all",
        choices=["all", "overview", "sales_overall", "individual_pack", "pack_release", "song_metrics"],
        help="Which dashboard to export (default: all)"
    )
    parser.add_argument(
        "--output-json", default=None,
        help="Save exported data to a JSON file (for debugging)"
    )

    args = parser.parse_args()

    exporter = BeatSaberExporter(
        api_key=args.api_key,
        dashboard_url=args.dashboard_url,
        start_date=args.start_date,
        end_date=args.end_date,
        namespace=args.namespace,
    )

    if args.dashboard == "all":
        results = exporter.export_all()
    else:
        method = getattr(exporter, f"export_{args.dashboard}")
        results = {args.dashboard: method()}

    if args.output_json:
        with open(args.output_json, "w") as f:
            json.dump(results, f, indent=2, default=str)
        print(f"\nData saved to {args.output_json}")


if __name__ == "__main__":
    main()
